# Generated by Django 5.1 on 2026-08-20 09:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HRMSapp', '0016_alter_companystructure_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(default='package', help_text="Lucide icon name for UI (e.g., 'laptop', 'monitor', 'phone')", max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Asset Categories',
                'db_table': 'asset_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_tag', models.CharField(help_text='Internal tag/barcode (e.g. AST-LAP-001)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='e.g. MacBook Pro 16 Inch', max_length=150)),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('model_number', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('vendor', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ALLOCATED', 'Allocated'), ('MAINTENANCE', 'Under Maintenance'), ('DISPOSED', 'Disposed / Written Off')], default='AVAILABLE', max_length=20)),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], default='NEW', max_length=10)),
                ('condition_notes', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='assets/images/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='HRMSapp.employee')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assetapp.assetcategory')),
            ],
            options={
                'db_table': 'assets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allocated_date', models.DateField(default=django.utils.timezone.now)),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('returned_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ALLOCATED', 'Allocated'), ('RETURNED', 'Returned'), ('DAMAGED', 'Damaged'), ('LOST', 'Lost / Stolen')], default='ALLOCATED', max_length=20)),
                ('handover_notes', models.TextField(blank=True, help_text='Notes at time of allocation (accessories, condition)', null=True)),
                ('return_notes', models.TextField(blank=True, help_text='Notes at time of return (condition, damages)', null=True)),
                ('recovery_cost', models.DecimalField(decimal_places=2, default=0, help_text='Amount to recover from employee (for damaged/lost items)', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='HRMSapp.employee')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='assetapp.asset')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_allocations', to='HRMSapp.employee')),
                ('returned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='HRMSapp.employee')),
            ],
            options={
                'db_table': 'asset_allocations',
                'ordering': ['-allocated_date'],
                'indexes': [models.Index(fields=['employee', 'status'], name='asset_alloc_employe_86a3c2_idx'), models.Index(fields=['asset', 'status'], name='asset_alloc_asset_i_8bdf72_idx'), models.Index(fields=['status', '-allocated_date'], name='asset_alloc_status_dfdbda_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['serial_number'], name='assets_serial__240171_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_tag'], name='assets_asset_t_3d9023_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['status'], name='assets_status_326766_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['category', 'status'], name='assets_categor_c87708_idx'),
        ),
    ]
