# Generated by Django 5.1 on 2026-07-14 12:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='aadhaar_number_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_account_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='pan_number_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='uan_number_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('grade_band', models.CharField(help_text="Grade band like 'G1', 'G2', 'M1', 'M2'", max_length=10)),
                ('budgeted_count', models.IntegerField(default=1, help_text='Approved headcount for FY')),
                ('actual_count', models.IntegerField(default=0, help_text='Currently filled headcount')),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(limit_choices_to={'type': 'DEPARTMENT'}, on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='HRMSapp.companystructure')),
            ],
            options={
                'db_table': 'job_positions',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='HRMSapp.jobposition'),
        ),
        migrations.CreateModel(
            name='EmployeeAuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=50)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_audit_logs', to='HRMSapp.employee')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changes_made', to='HRMSapp.employee')),
            ],
            options={
                'db_table': 'employee_audit_logs',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['employee', '-changed_at'], name='employee_au_employe_e177b7_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('CONTRACT', 'Employment Contract'), ('OFFER_LETTER', 'Offer Letter'), ('ID_PROOF', 'ID Proof'), ('ADDRESS_PROOF', 'Address Proof'), ('EDUCATION', 'Education Certificate'), ('EXPERIENCE', 'Experience Certificate'), ('PAN', 'PAN Card'), ('AADHAAR', 'Aadhaar Card'), ('PASSPORT', 'Passport'), ('VISA', 'Visa'), ('WORK_PERMIT', 'Work Permit'), ('MEDICAL', 'Medical Certificate'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('document_name', models.CharField(max_length=150)),
                ('file_path', models.FileField(upload_to='employee_documents/%Y/%m/')),
                ('file_size_kb', models.IntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('alert_fired_count', models.IntegerField(default=0, help_text='Number of expiry alerts already sent by Celery worker')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='HRMSapp.employee')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_documents', to='HRMSapp.employee')),
            ],
            options={
                'db_table': 'employee_documents',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['employee', 'document_type'], name='employee_do_employe_011309_idx'), models.Index(fields=['expiry_date'], name='employee_do_expiry__fa0ced_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='jobposition',
            constraint=models.CheckConstraint(condition=models.Q(('actual_count__lte', models.F('budgeted_count'))), name='chk_headcount_within_budget'),
        ),
        migrations.AddConstraint(
            model_name='jobposition',
            constraint=models.CheckConstraint(condition=models.Q(('budgeted_count__gte', 0)), name='chk_budgeted_count_positive'),
        ),
    ]
