# Generated by Django 5.1 on 2026-07-15 07:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSapp', '0002_employee_aadhaar_number_encrypted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(help_text='Unique setting key', max_length=100, unique=True)),
                ('value', models.CharField(help_text='Setting value', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_editable', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_settings', to='HRMSapp.employee')),
            ],
            options={
                'db_table': 'system_settings',
                'ordering': ['key'],
            },
        ),
    ]
