# Generated by Django 5.1 on 2026-07-15 10:09

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSapp', '0003_systemsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='aadhaar_number_encrypted',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, null=True)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bank_account_encrypted',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, null=True)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pan_number_encrypted',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, null=True)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='uan_number_encrypted',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, null=True)),
        ),
    ]
