# Generated by Django 5.1 on 2026-07-16 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSapp', '0004_alter_employee_aadhaar_number_encrypted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeauditlog',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes_made', to='HRMSapp.employee'),
        ),
    ]
