# Generated by Django 5.1 on 2026-07-17 08:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSapp', '0005_alter_employeeauditlog_modified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedocument',
            name='document_type',
            field=models.CharField(choices=[('CONTRACT', 'Employment Contract'), ('OFFER_LETTER', 'Offer Letter'), ('ID_PROOF', 'ID Proof'), ('ADDRESS_PROOF', 'Address Proof'), ('EDUCATION', 'Education Certificate'), ('EXPERIENCE', 'Experience Certificate'), ('PAN', 'PAN Card'), ('AADHAAR', 'Aadhaar Card'), ('PASSPORT', 'Passport'), ('VISA', 'Visa'), ('WORK_PERMIT', 'Work Permit'), ('MEDICAL', 'Medical Certificate'), ('LETTER_PROMOTION', 'Promotion Letter'), ('LETTER_TRANSFER', 'Transfer Letter'), ('LETTER_REDESIGNATION', 'Re-designation Letter'), ('LETTER_CONFIRMATION', 'Confirmation Letter'), ('LETTER_MANAGER_CHANGE', 'Manager Change Letter'), ('OTHER', 'Other')], default='OTHER', max_length=30),
        ),
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('module', models.CharField(choices=[('LIFECYCLE', 'Lifecycle Change')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflows', to='HRMSapp.employee')),
            ],
            options={
                'db_table': 'approval_workflows',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalWorkflowStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_number', models.IntegerField()),
                ('step_name', models.CharField(max_length=100)),
                ('approver_type', models.CharField(choices=[('REPORTING_MANAGER', 'Reporting Manager'), ('SKIP_LEVEL_MANAGER', 'Skip-Level Manager'), ('DEPARTMENT_HEAD', 'Department Head'), ('HR_ADMIN', 'Any HR Admin'), ('SYSTEM_ADMIN', 'Any System Admin'), ('SPECIFIC_EMPLOYEE', 'Specific Employee')], max_length=30)),
                ('sla_hours', models.IntegerField(default=48)),
                ('specific_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='HRMSapp.employee')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='HRMSapp.approvalworkflow')),
            ],
            options={
                'db_table': 'approval_workflow_steps',
                'ordering': ['workflow', 'step_number'],
            },
        ),
        migrations.CreateModel(
            name='LetterTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('template_type', models.CharField(choices=[('PROMOTION', 'Promotion Letter'), ('TRANSFER', 'Transfer Letter'), ('REDESIGNATION', 'Re-designation Letter'), ('CONFIRMATION', 'Confirmation Letter'), ('MANAGER_CHANGE', 'Manager Change Letter')], max_length=30)),
                ('subject', models.CharField(max_length=200)),
                ('body_html', models.TextField()),
                ('creation_method', models.CharField(choices=[('AI', 'AI Generated'), ('MANUAL', 'Manually Created'), ('AI_EDITED', 'AI Generated + Edited')], max_length=20)),
                ('ai_prompt', models.TextField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_letter_templates', to='HRMSapp.employee')),
            ],
            options={
                'db_table': 'letter_templates',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LifecycleChangeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_number', models.CharField(max_length=30, unique=True)),
                ('change_type', models.CharField(choices=[('PROMOTION', 'Promotion'), ('TRANSFER', 'Transfer'), ('REDESIGNATION', 'Re-designation'), ('MANAGER_CHANGE', 'Manager Change'), ('CONFIRMATION', 'Confirmation')], max_length=20)),
                ('current_status', models.CharField(blank=True, max_length=15)),
                ('proposed_status', models.CharField(blank=True, max_length=15)),
                ('effective_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('APPROVED', 'Approved & Applied'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='IN_PROGRESS', max_length=20)),
                ('current_step_number', models.IntegerField(default=1)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='HRMSapp.companystructure')),
                ('current_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='HRMSapp.employee')),
                ('current_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='HRMSapp.jobposition')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_requests', to='HRMSapp.employee')),
                ('generated_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='HRMSapp.employeedocument')),
                ('letter_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='HRMSapp.lettertemplate')),
                ('proposed_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='HRMSapp.companystructure')),
                ('proposed_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='HRMSapp.employee')),
                ('proposed_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='HRMSapp.jobposition')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raised_lifecycle_requests', to='HRMSapp.employee')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='HRMSapp.approvalworkflow')),
            ],
            options={
                'db_table': 'lifecycle_change_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LifecycleApprovalAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_number', models.IntegerField()),
                ('step_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('due_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pending_lifecycle_approvals', to='HRMSapp.employee')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_actions', to='HRMSapp.lifecyclechangerequest')),
            ],
            options={
                'db_table': 'lifecycle_approval_actions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('APPROVAL_REQUEST', 'Approval Request'), ('APPROVAL_APPROVED', 'Request Approved'), ('APPROVAL_REJECTED', 'Request Rejected'), ('LETTER_GENERATED', 'Letter Generated'), ('SYSTEM', 'System Notification')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, help_text='Frontend URL to navigate to', max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='HRMSapp.employee')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='approvalworkflow',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('module',), name='unique_active_workflow_per_module'),
        ),
        migrations.AlterUniqueTogether(
            name='approvalworkflowstep',
            unique_together={('workflow', 'step_number')},
        ),
        migrations.AddIndex(
            model_name='lifecycleapprovalaction',
            index=models.Index(fields=['assigned_to', 'status'], name='lifecycle_a_assigne_081b1c_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_dde14f_idx'),
        ),
    ]
