# Generated by Django 5.1 on 2026-07-18 11:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSapp', '0006_alter_employeedocument_document_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingScale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(help_text='1 to 5', unique=True)),
                ('label', models.CharField(help_text="e.g. 'Outstanding'", max_length=50)),
                ('description', models.TextField(blank=True)),
                ('min_percent', models.DecimalField(decimal_places=2, help_text='Minimum score % to qualify (e.g. 120.00)', max_digits=5)),
                ('max_percent', models.DecimalField(decimal_places=2, help_text='Maximum score % (use 999.00 for open-ended)', max_digits=5)),
                ('color_code', models.CharField(default='#3B82F6', help_text='Hex color for UI (e.g. #16A34A for green)', max_length=7)),
                ('triggers_pip', models.BooleanField(default=False, help_text='Triggers Performance Improvement Plan if TRUE')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rating_scales',
                'ordering': ['-rating'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentalKRA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('financial_year', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('weight_in_dept', models.DecimalField(decimal_places=2, default=10.0, help_text='Weight % within department objectives', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(limit_choices_to={'type': 'DEPARTMENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='departmental_kras', to='HRMSapp.companystructure')),
                ('owner', models.ForeignKey(blank=True, help_text='Department head or accountable person', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_dept_kras', to='HRMSapp.employee')),
            ],
            options={
                'db_table': 'departmental_kras',
                'ordering': ['department', '-financial_year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentalKPI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('kpi_type', models.CharField(choices=[('NUMERIC_UP', 'Numeric (Higher is Better)'), ('NUMERIC_DOWN', 'Numeric (Lower is Better)'), ('PERCENTAGE', 'Percentage'), ('RATING', 'Rating (1-5)'), ('BOOLEAN', 'Yes/No'), ('CURRENCY', 'Currency')], max_length=20)),
                ('formula', models.TextField(blank=True, help_text='How this KPI is calculated')),
                ('target', models.CharField(max_length=100)),
                ('data_source', models.CharField(blank=True, help_text='e.g. CRM, ERP, Manual', max_length=200)),
                ('weight', models.DecimalField(decimal_places=2, default=100.0, help_text='Weight % within this KRA', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dept_kra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='HRMSapp.departmentalkra')),
            ],
            options={
                'db_table': 'departmental_kpis',
                'ordering': ['dept_kra', 'name'],
            },
        ),
        migrations.CreateModel(
            name='KRALibrary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('kra_source', models.CharField(choices=[('ROLE', 'Role-Based (specific to job position)'), ('COMMON', 'Common (applies to all employees)'), ('DEPARTMENTAL', 'Departmental (specific to department)')], default='ROLE', max_length=20)),
                ('peer_rating_required', models.BooleanField(default=False, help_text='If TRUE, peers must rate this KRA during review')),
                ('is_mandatory', models.BooleanField(default=False, help_text="If TRUE, auto-added to every applicable employee's scorecard")),
                ('suggested_weight_min', models.DecimalField(decimal_places=2, default=5.0, help_text='Suggested minimum weight %', max_digits=5)),
                ('suggested_weight_max', models.DecimalField(decimal_places=2, default=30.0, help_text='Suggested maximum weight %', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_departments', models.ManyToManyField(blank=True, help_text='Which departments can use this KRA (empty = all)', limit_choices_to={'type': 'DEPARTMENT'}, related_name='library_kras', to='HRMSapp.companystructure')),
                ('applicable_positions', models.ManyToManyField(blank=True, help_text='Which job positions can use this KRA (empty = all)', related_name='library_kras', to='HRMSapp.jobposition')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_kras', to='HRMSapp.employee')),
            ],
            options={
                'db_table': 'kra_library',
                'ordering': ['kra_source', 'name'],
            },
        ),
        migrations.CreateModel(
            name='KPILibraryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('indicator_type', models.CharField(choices=[('OUTPUT', 'Output (Revenue, Volume)'), ('QUALITY', 'Quality (Defects, Complaints)'), ('EFFICIENCY', 'Efficiency (Cost, Time)'), ('TIMELINESS', 'Timeliness (On-time delivery)'), ('COMPLIANCE', 'Compliance (Audits)'), ('CAPABILITY', 'Capability (Skills, Training)')], default='OUTPUT', max_length=20)),
                ('kpi_type', models.CharField(choices=[('NUMERIC_UP', 'Numeric (Higher is Better)'), ('NUMERIC_DOWN', 'Numeric (Lower is Better)'), ('PERCENTAGE', 'Percentage'), ('RATING', 'Rating (1-5)'), ('BOOLEAN', 'Yes/No'), ('CURRENCY', 'Currency')], default='NUMERIC_UP', max_length=20)),
                ('default_formula', models.TextField(blank=True, help_text="e.g. 'Total revenue / Number of clients'")),
                ('default_data_source', models.CharField(blank=True, help_text="e.g. 'CRM Dashboard'", max_length=200)),
                ('measurement_frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('HALF_YEARLY', 'Half-Yearly'), ('YEARLY', 'Yearly')], default='QUARTERLY', max_length=20)),
                ('suggested_baseline', models.CharField(blank=True, max_length=100)),
                ('suggested_target_minimum', models.CharField(blank=True, max_length=100)),
                ('suggested_target_expected', models.CharField(blank=True, max_length=100)),
                ('suggested_target_exceptional', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_options', to='HRMSapp.kralibrary')),
            ],
            options={
                'db_table': 'kpi_library_items',
                'ordering': ['kra', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationalPriority',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('financial_year', models.CharField(help_text="e.g. 'FY 2026-27'", max_length=20)),
                ('priority_number', models.IntegerField(help_text='Priority rank (1-8)')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('target', models.CharField(help_text="Organizational target (e.g. 'Grow revenue by 20%')", max_length=200)),
                ('review_frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('HALF_YEARLY', 'Half-Yearly'), ('YEARLY', 'Yearly')], default='QUARTERLY', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_org_priorities', to='HRMSapp.employee')),
                ('owner', models.ForeignKey(blank=True, help_text='Executive owner (CFO, CTO, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_org_priorities', to='HRMSapp.employee')),
            ],
            options={
                'db_table': 'organizational_priorities',
                'ordering': ['financial_year', 'priority_number'],
                'unique_together': {('financial_year', 'priority_number')},
            },
        ),
        migrations.AddField(
            model_name='departmentalkra',
            name='linked_priority',
            field=models.ForeignKey(blank=True, help_text='Which org priority this KRA supports', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departmental_kras', to='HRMSapp.organizationalpriority'),
        ),
    ]
