# Generated by Django 5.1 on 2026-07-18 12:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSapp', '0007_ratingscale_departmentalkra_departmentalkpi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeKPI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('indicator_type', models.CharField(choices=[('OUTPUT', 'Output'), ('QUALITY', 'Quality'), ('EFFICIENCY', 'Efficiency'), ('TIMELINESS', 'Timeliness'), ('COMPLIANCE', 'Compliance'), ('CAPABILITY', 'Capability')], default='OUTPUT', max_length=20)),
                ('kpi_type', models.CharField(choices=[('NUMERIC_UP', 'Numeric (Higher is Better)'), ('NUMERIC_DOWN', 'Numeric (Lower is Better)'), ('PERCENTAGE', 'Percentage'), ('RATING', 'Rating (1-5)'), ('BOOLEAN', 'Yes/No'), ('CURRENCY', 'Currency')], max_length=20)),
                ('formula', models.TextField(blank=True)),
                ('baseline', models.CharField(blank=True, max_length=100)),
                ('target_minimum', models.CharField(blank=True, max_length=100)),
                ('target_expected', models.CharField(max_length=100)),
                ('target_exceptional', models.CharField(blank=True, max_length=100)),
                ('data_source', models.CharField(blank=True, max_length=200)),
                ('weight_in_kra', models.DecimalField(decimal_places=2, default=100.0, help_text='Weight % within its KRA', max_digits=5)),
                ('action_plan', models.TextField(blank=True, help_text="Employee's plan for how they'll achieve target")),
                ('self_actual', models.CharField(blank=True, max_length=200)),
                ('self_rating', models.IntegerField(blank=True, help_text='1-5', null=True)),
                ('self_comment', models.TextField(blank=True)),
                ('self_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('manager_actual', models.CharField(blank=True, max_length=200)),
                ('manager_rating', models.IntegerField(blank=True, help_text='1-5', null=True)),
                ('manager_comment', models.TextField(blank=True)),
                ('manager_override_reason', models.TextField(blank=True, help_text='Reason if manager_actual differs from self_actual')),
                ('manager_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('weighted_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('library_kpi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_kpis', to='HRMSapp.kpilibraryitem')),
            ],
            options={
                'db_table': 'employee_kpis',
                'ordering': ['employee_kra', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeKPIEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='kpi_evidences/%Y/%m/')),
                ('file_name', models.CharField(max_length=200)),
                ('file_size_kb', models.IntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='HRMSapp.employeekpi')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_kpi_evidences', to='HRMSapp.employee')),
            ],
            options={
                'db_table': 'employee_kpi_evidences',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeKRA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight % within scorecard', max_digits=5)),
                ('peer_rating_required', models.BooleanField(default=False)),
                ('kra_source', models.CharField(choices=[('LIBRARY', 'From KRA Library'), ('CUSTOM', 'Custom (Manager/Employee Added)'), ('MANDATORY', 'Mandatory (Auto-added)'), ('INHERITED', 'Inherited (from dept/common)')], default='LIBRARY', max_length=20)),
                ('rationale', models.TextField(blank=True, help_text='Why the employee/manager included this KRA')),
                ('kra_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('library_kra', models.ForeignKey(blank=True, help_text='Source library KRA (nullable if custom)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_kras', to='HRMSapp.kralibrary')),
                ('linked_priority', models.ForeignKey(blank=True, help_text='Which org priority this KRA supports', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='HRMSapp.organizationalpriority')),
            ],
            options={
                'db_table': 'employee_kras',
                'ordering': ['scorecard', 'display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='employeekpi',
            name='employee_kra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='HRMSapp.employeekra'),
        ),
        migrations.CreateModel(
            name='EmployeeScorecard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft - Employee Building'), ('SUBMITTED', 'Submitted for Manager Review'), ('MANAGER_REVIEWING', 'Manager Reviewing'), ('SENT_BACK', 'Sent Back for Revision'), ('APPROVED', 'Approved by Manager'), ('SIGNED_OFF', 'Signed Off - Active'), ('SELF_REVIEW_PENDING', 'Self Review Pending'), ('SELF_REVIEWED', 'Self Review Complete'), ('MANAGER_REVIEW_PENDING', 'Final Review Pending'), ('MANAGER_REVIEWED', 'Final Review Complete'), ('FINALIZED', 'Finalized')], default='DRAFT', max_length=30)),
                ('employee_signed_off_at', models.DateTimeField(blank=True, null=True)),
                ('manager_signed_off_at', models.DateTimeField(blank=True, null=True)),
                ('sent_back_reason', models.TextField(blank=True, null=True)),
                ('sent_back_at', models.DateTimeField(blank=True, null=True)),
                ('self_score', models.DecimalField(blank=True, decimal_places=2, help_text="Employee's self-assessment score", max_digits=6, null=True)),
                ('peer_score', models.DecimalField(blank=True, decimal_places=2, help_text='Aggregated peer score', max_digits=6, null=True)),
                ('manager_score', models.DecimalField(blank=True, decimal_places=2, help_text="Manager's assessment score", max_digits=6, null=True)),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, help_text='Auto-calculated final weighted score', max_digits=6, null=True)),
                ('final_rating', models.IntegerField(blank=True, help_text='Rating band (1-5) based on final_score', null=True)),
                ('total_weight', models.DecimalField(decimal_places=2, default=0, help_text='Sum of all KRA weights (should be 100)', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorecards', to='HRMSapp.employee')),
                ('manager_signed_off_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_signoffs', to='HRMSapp.employee')),
            ],
            options={
                'db_table': 'employee_scorecards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='employeekra',
            name='scorecard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kras', to='HRMSapp.employeescorecard'),
        ),
        migrations.CreateModel(
            name='PerformanceCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="e.g. 'FY 2026 Q1 Review'", max_length=150)),
                ('cycle_type', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('HALF_YEARLY', 'Half-Yearly'), ('YEARLY', 'Yearly')], max_length=20)),
                ('financial_year', models.CharField(help_text="e.g. 'FY 2026-27'", max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('goal_setting_start', models.DateField(help_text='Employee builds scorecard')),
                ('goal_setting_end', models.DateField()),
                ('manager_review_start', models.DateField(help_text='Manager reviews & customizes scorecard')),
                ('manager_review_end', models.DateField()),
                ('working_start', models.DateField(help_text='Working period begins')),
                ('working_end', models.DateField()),
                ('peer_rating_start', models.DateField(help_text='Peer rating window')),
                ('peer_rating_end', models.DateField()),
                ('self_review_start', models.DateField(help_text='Employee self-review')),
                ('self_review_end', models.DateField()),
                ('final_review_start', models.DateField(help_text='Manager final review & scoring')),
                ('final_review_end', models.DateField()),
                ('finalization_start', models.DateField(help_text='HR closes cycle')),
                ('finalization_end', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_departments', models.ManyToManyField(blank=True, help_text='Departments this cycle applies to (empty = all)', limit_choices_to={'type': 'DEPARTMENT'}, related_name='performance_cycles', to='HRMSapp.companystructure')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_perf_cycles', to='HRMSapp.employee')),
            ],
            options={
                'db_table': 'performance_cycles',
                'ordering': ['-period_start'],
            },
        ),
        migrations.AddField(
            model_name='employeescorecard',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorecards', to='HRMSapp.performancecycle'),
        ),
        migrations.AddIndex(
            model_name='employeescorecard',
            index=models.Index(fields=['employee', 'cycle'], name='employee_sc_employe_4c6d20_idx'),
        ),
        migrations.AddIndex(
            model_name='employeescorecard',
            index=models.Index(fields=['status', '-created_at'], name='employee_sc_status_10150e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employeescorecard',
            unique_together={('employee', 'cycle')},
        ),
    ]
