# Generated by Django 5.1 on 2026-07-18 13:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSapp', '0008_employeekpi_employeekpievidence_employeekra_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KRAPeerNomination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nominated_at', models.DateTimeField(auto_now_add=True)),
                ('employee_kra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_nominations', to='HRMSapp.employeekra')),
                ('nominated_by', models.ForeignKey(blank=True, help_text='Manager who selected this peer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peer_nominations_made', to='HRMSapp.employee')),
                ('nominated_peer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_nominations_received', to='HRMSapp.employee')),
            ],
            options={
                'db_table': 'kra_peer_nominations',
                'ordering': ['-nominated_at'],
            },
        ),
        migrations.CreateModel(
            name='PeerRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(blank=True, help_text='1-5 rating scale', null=True)),
                ('strengths_comment', models.TextField(blank=True, help_text='What the person does well (HR/Manager only)')),
                ('improvements_comment', models.TextField(blank=True, help_text='Areas for improvement (HR/Manager only)')),
                ('additional_comments', models.TextField(blank=True, help_text='Any other feedback (HR/Manager only)')),
                ('is_anonymous_to_employee', models.BooleanField(default=True, help_text='If TRUE, employee never sees which peer gave which rating')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('DECLINED', 'Declined')], default='PENDING', max_length=20)),
                ('decline_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, help_text="Deadline based on cycle's peer_rating_end date", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nomination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='HRMSapp.krapeernomination')),
            ],
            options={
                'db_table': 'peer_ratings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='krapeernomination',
            index=models.Index(fields=['nominated_peer', '-nominated_at'], name='kra_peer_no_nominat_bc2c48_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='krapeernomination',
            unique_together={('employee_kra', 'nominated_peer')},
        ),
        migrations.AddIndex(
            model_name='peerrating',
            index=models.Index(fields=['status', 'due_at'], name='peer_rating_status_5dca32_idx'),
        ),
    ]
