# Generated by Django 5.1 on 2026-07-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSapp', '0011_passwordresetotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalworkflow',
            name='module',
            field=models.CharField(choices=[('LIFECYCLE', 'Lifecycle Change'), ('LEAVE', 'Leave Application')], max_length=30),
        ),
    ]
