# Generated by Django 5.1 on 2026-07-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSapp', '0012_alter_approvalworkflow_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lettertemplate',
            name='template_type',
            field=models.CharField(choices=[('PROMOTION', 'Promotion Letter'), ('TRANSFER', 'Transfer Letter'), ('REDESIGNATION', 'Re-designation Letter'), ('CONFIRMATION', 'Confirmation Letter'), ('MANAGER_CHANGE', 'Manager Change Letter'), ('PERFORMANCE_RATING', 'Performance Rating Letter'), ('APPRAISAL_LETTER', 'Appraisal Letter'), ('PIP_LETTER', 'Performance Improvement Plan Letter'), ('LEAVE_APPLICATION', 'Leave Application Letter'), ('LEAVE_APPROVAL', 'Leave Approval Letter')], max_length=30),
        ),
    ]
