# Generated by Django 5.1 on 2026-07-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSapp', '0013_alter_lettertemplate_template_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalworkflow',
            name='module',
            field=models.CharField(choices=[('LIFECYCLE', 'Lifecycle Change'), ('LEAVE', 'Leave Application'), ('POLICY', 'Policy Approval')], max_length=30),
        ),
    ]
