# Generated by Django 5.1 on 2026-07-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSapp', '0014_alter_approvalworkflow_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalworkflow',
            name='module',
            field=models.CharField(choices=[('LIFECYCLE', 'Lifecycle Change'), ('LEAVE', 'Leave Application'), ('POLICY', 'Policy Approval'), ('CALENDAR', 'Annual Calendar')], max_length=30),
        ),
    ]
