# Generated by Django 5.1 on 2026-07-31 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSapp', '0015_alter_approvalworkflow_module'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companystructure',
            options={'ordering': ['level', 'name']},
        ),
        migrations.AddField(
            model_name='companystructure',
            name='color_code',
            field=models.CharField(blank=True, default='#3B82F6', max_length=7),
        ),
        migrations.AddField(
            model_name='companystructure',
            name='display_name',
            field=models.CharField(blank=True, help_text="Custom display label (e.g., 'Branch' instead of 'Location')", max_length=100),
        ),
        migrations.AddField(
            model_name='companystructure',
            name='icon',
            field=models.CharField(blank=True, default='building', max_length=50),
        ),
        migrations.AddField(
            model_name='companystructure',
            name='level',
            field=models.IntegerField(default=1, help_text='Auto-set from type (1=Company, 7=Cost Center)'),
        ),
        migrations.AddField(
            model_name='companystructure',
            name='path',
            field=models.CharField(blank=True, db_index=True, help_text='Cached hierarchy path: /Company/Location/Department', max_length=500),
        ),
        migrations.AddField(
            model_name='employee',
            name='cost_center',
            field=models.ForeignKey(blank=True, help_text='Financial cost center for reporting', limit_choices_to={'type': 'COST_CENTER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cc_employees', to='HRMSapp.companystructure'),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Which department/team the employee belongs to', limit_choices_to={'type__in': ['DEPARTMENT', 'TEAM']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept_employees', to='HRMSapp.companystructure'),
        ),
        migrations.AddField(
            model_name='employee',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Which physical location/office', limit_choices_to={'type__in': ['LOCATION', 'HQ', 'COMPANY']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_employees', to='HRMSapp.companystructure'),
        ),
        migrations.AlterField(
            model_name='companystructure',
            name='type',
            field=models.CharField(choices=[('COMPANY', 'Company'), ('HQ', 'Headquarters'), ('BUSINESS_UNIT', 'Business Unit'), ('LOCATION', 'Location'), ('DEPARTMENT', 'Department'), ('TEAM', 'Team'), ('COST_CENTER', 'Cost Center')], max_length=20),
        ),
    ]
