# Generated by Django 5.1 on 2026-08-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSapp', '0016_alter_companystructure_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lettertemplate',
            name='template_type',
            field=models.CharField(choices=[('PROMOTION', 'Promotion Letter'), ('TRANSFER', 'Transfer Letter'), ('REDESIGNATION', 'Re-designation Letter'), ('CONFIRMATION', 'Confirmation Letter'), ('MANAGER_CHANGE', 'Manager Change Letter'), ('PERFORMANCE_RATING', 'Performance Rating Letter'), ('APPRAISAL_LETTER', 'Appraisal Letter'), ('PIP_LETTER', 'Performance Improvement Plan Letter'), ('LEAVE_APPLICATION', 'Leave Application Letter'), ('LEAVE_APPROVAL', 'Leave Approval Letter'), ('ASSET_ALLOCATION', 'Asset Allocation Letter')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('APPROVAL_REQUEST', 'Approval Request'), ('APPROVAL_APPROVED', 'Request Approved'), ('APPROVAL_REJECTED', 'Request Rejected'), ('LETTER_GENERATED', 'Letter Generated'), ('SYSTEM', 'System Notification'), ('ASSET_ALLOCATED', 'Asset Allocated')], max_length=30),
        ),
    ]
