# Generated by Django 5.1

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSapp', '0018_alter_lettertemplate_template_type_and_more'),
    ]

    operations = [
        # =========================================================
        # 1. DELETE OLD PERFORMANCE MODELS DIRECTLY (NO REMOVEFIELD)
        # =========================================================
        migrations.DeleteModel(name='EmployeeKPIEvidence'),
        migrations.DeleteModel(name='EmployeeKPI'),
        migrations.DeleteModel(name='PeerRating'),
        migrations.DeleteModel(name='KRAPeerNomination'),
        migrations.DeleteModel(name='EmployeeKRA'),
        migrations.DeleteModel(name='EmployeeScorecard'),
        migrations.DeleteModel(name='PerformanceCycle'),

        # =========================================================
        # 2. CREATE NEW PERFORMANCE MODELS
        # =========================================================
        migrations.CreateModel(
            name='AnnualPerformancePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('financial_year', models.CharField(help_text="e.g. '2026-27'", max_length=20)),
                ('plan_start_date', models.DateField()),
                ('plan_end_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active / In Progress'), ('CLOSED', 'Closed (Year End)')], default='DRAFT', max_length=20)),
                ('annual_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('annual_rating', models.IntegerField(blank=True, help_text='1-5 rating', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='HRMSapp.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_plans', to='HRMSapp.employee')),
            ],
            options={
                'db_table': 'perf_annual_plans',
                'ordering': ['-financial_year', 'employee'],
                'unique_together': {('employee', 'financial_year')},
            },
        ),
        migrations.CreateModel(
            name='QuarterlyReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quarter', models.CharField(choices=[('Q1', 'Q1 (Apr-Jun)'), ('Q2', 'Q2 (Jul-Sep)'), ('Q3', 'Q3 (Oct-Dec)'), ('Q4', 'Q4 (Jan-Mar)')], max_length=2)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('quarterly_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('quarterly_rating', models.IntegerField(blank=True, null=True)),
                ('manager_comments', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('annual_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarterly_reviews', to='HRMSapp.annualperformanceplan')),
            ],
            options={
                'db_table': 'perf_quarterly_reviews',
                'ordering': ['annual_plan', 'quarter'],
                'unique_together': {('annual_plan', 'quarter')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyPerformancePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.IntegerField(help_text='1=Jan, 4=Apr, etc.')),
                ('year', models.IntegerField(help_text='e.g. 2026')),
                ('month_start_date', models.DateField()),
                ('month_end_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open (Working phase)'), ('REVIEW_DUE', 'Review Due'), ('EMPLOYEE_SUBMITTED', 'Employee Submitted'), ('UNDER_REVIEW', 'Manager Reviewing'), ('RETURNED', 'Returned to Employee'), ('APPROVED', 'Manager Approved'), ('CLOSED', 'Closed (Immutable)')], default='DRAFT', max_length=30)),
                ('monthly_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('employee_comments', models.TextField(blank=True)),
                ('manager_comments', models.TextField(blank=True)),
                ('employee_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('manager_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('annual_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_plans', to='HRMSapp.annualperformanceplan')),
                ('quarterly_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_plans', to='HRMSapp.quarterlyreview')),
            ],
            options={
                'db_table': 'perf_monthly_plans',
                'ordering': ['year', 'month'],
                'unique_together': {('annual_plan', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyKRA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kra_type', models.CharField(choices=[('COMMON', 'Common KRA'), ('DEPARTMENTAL', 'Departmental KRA'), ('INDIVIDUAL', 'Individual KRA')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('kra_start_date', models.DateField()),
                ('kra_end_date', models.DateField()),
                ('kra_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('monthly_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kras', to='HRMSapp.monthlyperformanceplan')),
                ('source_dept_kra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='HRMSapp.departmentalkra')),
                ('source_library_kra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='HRMSapp.kralibrary')),
            ],
            options={
                'db_table': 'perf_monthly_kras',
                'ordering': ['monthly_plan', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyKPI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('metric_type', models.CharField(choices=[('NUMERIC_UP', 'Numeric (Higher is Better)'), ('NUMERIC_DOWN', 'Numeric (Lower is Better)'), ('PERCENTAGE', 'Percentage'), ('RATING', 'Rating (1-5)'), ('BOOLEAN', 'Yes/No')], default='NUMERIC_UP', max_length=20)),
                ('weight_in_kra', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('target_value', models.CharField(max_length=100)),
                ('actual_value', models.CharField(blank=True, max_length=100)),
                ('achievement_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('employee_comment', models.TextField(blank=True)),
                ('manager_comment', models.TextField(blank=True)),
                ('manager_rating', models.IntegerField(blank=True, help_text='1-5 rating', null=True)),
                ('weighted_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('monthly_kra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='HRMSapp.monthlykra')),
            ],
            options={
                'db_table': 'perf_monthly_kpis',
                'ordering': ['monthly_kra', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyKPIEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='monthly_kpi_evidences/%Y/%m/')),
                ('file_name', models.CharField(max_length=200)),
                ('file_size_kb', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='HRMSapp.monthlykpi')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='HRMSapp.employee')),
            ],
            options={
                'db_table': 'perf_monthly_kpi_evidences',
            },
        ),
    ]