# Generated by Django 5.1 on 2026-08-21 11:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSapp', '0019_monthlykpi_remove_employeekpievidence_kpi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarryForwardRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_month_name', models.CharField(max_length=20)),
                ('shortfall_amount', models.CharField(max_length=100)),
                ('destination_month_name', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved & Applied'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annual_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carry_forwards', to='HRMSapp.annualperformanceplan')),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='HRMSapp.employee')),
                ('destination_kpi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carried_forward_to', to='HRMSapp.monthlykpi')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='HRMSapp.employee')),
                ('source_kpi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carried_forward_from', to='HRMSapp.monthlykpi')),
            ],
            options={
                'db_table': 'perf_carry_forward_records',
            },
        ),
        migrations.CreateModel(
            name='CommonKRAMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('financial_year', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('default_weight', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('applies_to_all', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'perf_common_kra_master',
                'unique_together': {('financial_year', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CommonKPIMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('metric_type', models.CharField(default='NUMERIC_UP', max_length=20)),
                ('default_target', models.CharField(max_length=200)),
                ('weight_in_kra', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('common_kra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='HRMSapp.commonkramaster')),
            ],
            options={
                'db_table': 'perf_common_kpi_master',
            },
        ),
        migrations.CreateModel(
            name='DepartmentalKRAMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('financial_year', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('default_weight', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRMSapp.companystructure')),
            ],
            options={
                'db_table': 'perf_dept_kra_master',
                'unique_together': {('financial_year', 'department', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DepartmentalKPIMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('metric_type', models.CharField(default='NUMERIC_UP', max_length=20)),
                ('default_target', models.CharField(max_length=200)),
                ('weight_in_kra', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('dept_kra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='HRMSapp.departmentalkramaster')),
            ],
            options={
                'db_table': 'perf_dept_kpi_master',
            },
        ),
    ]
