# Generated by Django 5.1 on 2026-08-21 12:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSapp', '0020_carryforwardrecord_commonkramaster_commonkpimaster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlykra',
            name='peer_rating_required',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MonthlyPeerNomination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('monthly_kra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_nominations', to='HRMSapp.monthlykra')),
                ('nominated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_peer_nominations_made', to='HRMSapp.employee')),
                ('nominated_peer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_peer_nominations_received', to='HRMSapp.employee')),
            ],
            options={
                'db_table': 'perf_monthly_peer_nominations',
                'ordering': ['-created_at'],
                'unique_together': {('monthly_kra', 'nominated_peer')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyPeerRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('DECLINED', 'Declined')], default='PENDING', max_length=20)),
                ('rating', models.IntegerField(blank=True, help_text='1-5', null=True)),
                ('strengths_comment', models.TextField(blank=True)),
                ('improvements_comment', models.TextField(blank=True)),
                ('additional_comments', models.TextField(blank=True)),
                ('decline_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nomination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='HRMSapp.monthlypeernomination')),
            ],
            options={
                'db_table': 'perf_monthly_peer_ratings',
                'ordering': ['-created_at'],
            },
        ),
    ]
