# Generated by Django 5.1 on 2026-08-24 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSapp', '0021_monthlykra_peer_rating_required_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlykra',
            name='source_library_kra',
        ),
        migrations.AddField(
            model_name='monthlykra',
            name='source_common_kra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='HRMSapp.commonkramaster'),
        ),
        migrations.AlterField(
            model_name='monthlykra',
            name='source_dept_kra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='HRMSapp.departmentalkramaster'),
        ),
    ]
