# Generated by Django 5.1 on 2026-08-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSapp', '0022_remove_monthlykra_source_library_kra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlykpi',
            name='manager_actual',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
