# Generated by Django 5.1 on 2026-08-31 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSapp', '0023_monthlykpi_manager_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='companystructure',
            name='department_head',
            field=models.ForeignKey(blank=True, help_text='The HOD for this department', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='HRMSapp.employee'),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
