# Generated by Django 5.1 on 2026-09-01 06:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSapp', '0024_companystructure_department_head_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyLogo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('logo', models.ImageField(upload_to='company_logos/')),
                ('dark_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('tagline', models.CharField(blank=True, default='', max_length=255)),
                ('company_url', models.URLField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'company_logos',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
