# Generated by Django 5.1 on 2026-09-01 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSapp', '0025_companylogo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companylogo',
            name='dark_logo',
        ),
    ]
