# Generated by Django 5.1 on 2026-09-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSapp', '0026_remove_companylogo_dark_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='can_self_attend',
            field=models.BooleanField(default=False, help_text='If True, employee can self-report WFH/Site Visit from their calendar. Auto-True when work_mode is WFH/HYBRID.'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_mode',
            field=models.CharField(choices=[('REGULAR', 'Regular (On-Site)'), ('WFH', 'Work From Home'), ('HYBRID', 'Hybrid')], default='REGULAR', help_text='REGULAR = must punch on device, WFH = can self-report, HYBRID = both', max_length=10),
        ),
    ]
