# """
# Django settings for HRMS project.

# Generated by 'django-admin startproject' using Django 5.1.3.

# For more information on this file, see
# https://docs.djangoproject.com/en/5.1/topics/settings/

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/5.1/ref/settings/
# """

# from pathlib import Path

# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent


# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-xe*qt94)9$9dc(v7rw7r9jdp4nexn5lr4$zyyua5liyr4b!7xh'

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# ALLOWED_HOSTS = []


# # Application definition

# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
# ]

# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# ]

# ROOT_URLCONF = 'HRMS.urls'

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = 'HRMS.wsgi.application'


# # Database
# # https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# # Password validation
# # https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]


# # Internationalization
# # https://docs.djangoproject.com/en/5.1/topics/i18n/

# LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'

# USE_I18N = True

# USE_TZ = True


# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/5.1/howto/static-files/

# STATIC_URL = 'static/'

# # Default primary key field type
# # https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



"""
Django settings for HRMS project.
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# ==============================================================================
# BASE CONFIGURATION
# ==============================================================================

BASE_DIR = Path(__file__).resolve().parent.parent

# ==============================================================================
# DOCKER DETECTION
# ==============================================================================

# Detect if running inside Docker container
# Docker sets specific environment variables or creates /.dockerenv file
RUNNING_IN_DOCKER = os.path.exists('/.dockerenv') or os.getenv('RUNNING_IN_DOCKER', 'False') == 'True'

# ==============================================================================
# SECURITY SETTINGS
# ==============================================================================

SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-change-me')

DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = os.getenv(
    'DJANGO_ALLOWED_HOSTS',
    'localhost,127.0.0.1'
).split(',')

FIELD_ENCRYPTION_KEY = os.getenv(
    'FIELD_ENCRYPTION_KEY',
    'CUzLvcic0EfwYGtteQg8tbK_ri0Lq3cCATxF22UYiog='  # ← Replace with key from Step 2
)

CRYPTOGRAPHY_KEY = FIELD_ENCRYPTION_KEY
CRYPTOGRAPHY_SALT = os.getenv('CRYPTOGRAPHY_SALT', 'hrms-pii-salt-change-me')
CRYPTOGRAPHY_BACKEND = 'cryptography.hazmat.backends.default_backend'
# ==============================================================================
# APPLICATION DEFINITION
# ==============================================================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps (add as needed)
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'django_celery_beat',        # ← ADD
    'django_celery_results',
    # Your apps (add your apps here)
    'HRMSapp',  # Your app
    'reimbursementapp',   
    'attendanceapp',
    'leaveapp',
    'policyapp',
    'assetapp',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware', 
]

ROOT_URLCONF = 'HRMS.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'HRMS.wsgi.application'

# ==============================================================================
# DATABASE CONFIGURATION
# ==============================================================================

DATABASE_ENGINE = os.getenv("DATABASE_ENGINE", "django.db.backends.sqlite3")

if DATABASE_ENGINE == "django.db.backends.sqlite3":
    # ---------------- SQLite (Development) ----------------
    DATABASES = {
        "default": {
            "ENGINE": DATABASE_ENGINE,
            "NAME": BASE_DIR / os.getenv("DATABASE_NAME", "db.sqlite3"),
        }
    }
    print("[HRMS Settings] Database: SQLite (Development)")

else:
    # ---------------- PostgreSQL (Production) ----------------
    database_host = os.getenv("DATABASE_HOST", "postgres")
    
    # If not running in Docker, use localhost instead of 'postgres'
    if not RUNNING_IN_DOCKER and database_host == "postgres":
        database_host = "127.0.0.1"

    DATABASES = {
        "default": {
            "ENGINE": DATABASE_ENGINE,
            "NAME": os.getenv("DATABASE_NAME", "hrms_prod"),
            "USER": os.getenv("DATABASE_USER", "postgres"),
            "PASSWORD": os.getenv("DATABASE_PASSWORD", ""),
            "HOST": database_host,
            "PORT": os.getenv("DATABASE_PORT", "5432"),
        }
    }
    print(f"[HRMS Settings] Database: PostgreSQL (Production) - Host: {database_host}")

# ==============================================================================
# CORS / CSRF SETTINGS
# ==============================================================================

CORS_ALLOW_ALL_ORIGINS = os.getenv('CORS_ALLOW_ALL_ORIGINS', 'False').lower() == 'true'

CORS_ALLOWED_ORIGINS = os.getenv(
    'CORS_ALLOWED_ORIGINS',
    'http://localhost:5173,http://127.0.0.1:5173'
).split(',')

CSRF_TRUSTED_ORIGINS = os.getenv(
    'CSRF_TRUSTED_ORIGINS',
    'http://localhost:5173,http://127.0.0.1:5173'
).split(',')

CORS_ALLOW_CREDENTIALS = True

# ==============================================================================
# PASSWORD VALIDATION
# ==============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'HRMSapp.UserAccount'
# ==============================================================================
# DJANGO REST FRAMEWORK
# ==============================================================================

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# ==============================================================================
# JWT SETTINGS
# ==============================================================================

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),          # Access token valid for 1 hour
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),          # Refresh token valid for 7 days
    'ROTATE_REFRESH_TOKENS': True,                        # New refresh token on each refresh
    'BLACKLIST_AFTER_ROTATION': True,                     # Old tokens become invalid
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

# ==============================================================================
# COMPANY SETTINGS
# ==============================================================================
CORS_ALLOW_METHODS = [
    'DELETE', 'GET', 'OPTIONS', 'PATCH', 'POST', 'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept', 'accept-encoding', 'authorization', 'content-type',
    'dnt', 'origin', 'user-agent', 'x-csrftoken', 'x-requested-with',
]


# Login security
MAX_LOGIN_ATTEMPTS = 5
LOGIN_LOCKOUT_DURATION_MINUTES = 30
# ==============================================================================
# INTERNATIONALIZATION
# ==============================================================================

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'  # Change to your timezone
USE_I18N = True
USE_TZ = True

# ==============================================================================
# STATIC & MEDIA FILES
# ==============================================================================

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024        # 5 MB in memory before switching to disk
DATA_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024        # 5 MB total request in memory

# Maximum total file size allowed per upload (20 MB)
MAX_UPLOAD_SIZE = 20 * 1024 * 1024                   # ← 20 MB

DATA_UPLOAD_MAX_NUMBER_FILES = 20
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000

FILE_UPLOAD_TEMP_DIR = None
FILE_UPLOAD_PERMISSIONS = 0o644
FILE_UPLOAD_DIRECTORY_PERMISSIONS = 0o755

FILE_UPLOAD_HANDLERS = [
    'django.core.files.uploadhandler.MemoryFileUploadHandler',
    'django.core.files.uploadhandler.TemporaryFileUploadHandler',
]
# ==============================================================================
# DEFAULT PRIMARY KEY
# ==============================================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==============================================================================
# CELERY CONFIGURATION
# ==============================================================================

CELERY_BROKER_URL = os.getenv('REDIS_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = 'django-db'

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 min max per task

CELERY_TASK_ALWAYS_EAGER = os.getenv('CELERY_EAGER', 'False').lower() == 'true'
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'


# ==============================================================================
# EMAIL CONFIGURATION
# ==============================================================================

EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'HRMS <noreply@hrms.com>')
EMAIL_TIMEOUT = 30

HR_NOTIFICATION_EMAIL = os.getenv('HR_NOTIFICATION_EMAIL', 'hr@hrms.com')
PORTAL_URL = os.getenv('PORTAL_URL', 'http://localhost:5173')

# ==============================================================================
# GROQ AI CONFIGURATION
# ==============================================================================
GROQ_API_KEY = os.getenv('GROQ_API_KEY', '')
GROQ_MODEL = os.getenv('GROQ_MODEL', 'llama-3.1-8b-instant')


# ==============================================================================
# COMPANY BRANDING FOR HR LETTER PDF
# ==============================================================================

COMPANY_NAME = os.getenv('COMPANY_NAME', 'NL Technologies Pvt Ltd')
COMPANY_TAGLINE = os.getenv('COMPANY_TAGLINE', 'Excellence in Every Endeavor')
COMPANY_ADDRESS = os.getenv('COMPANY_ADDRESS', '123 Business Park, Bengaluru, KA 560001')
COMPANY_PHONE = os.getenv('COMPANY_PHONE', '+91 80 4567 8900')
COMPANY_EMAIL = os.getenv('COMPANY_EMAIL', 'hr@nltechsolutions.com')
COMPANY_WEBSITE = os.getenv('COMPANY_WEBSITE', 'www.nltechsolutions.com')

# Optional local logo path. Example:
# COMPANY_LOGO_PATH=C:\Users\HP\Documents\Django\HRMS\media\company\logo.png
COMPANY_LOGO_PATH = os.getenv('COMPANY_LOGO_PATH', '')

COMPANY_PRIMARY_COLOR = os.getenv('COMPANY_PRIMARY_COLOR', '#1E40AF')
COMPANY_ACCENT_COLOR = os.getenv('COMPANY_ACCENT_COLOR', '#3B82F6')



# ==============================================================================
# REIMBURSEMENT APP SETTINGS
# ==============================================================================

# Tesseract OCR path
TESSERACT_CMD = os.getenv(
    "TESSERACT_CMD",
    r"C:\Program Files\Tesseract-OCR\tesseract.exe"
)

# Quick Claim limits
QUICK_CLAIM_MAX_FILES = int(os.getenv("QUICK_CLAIM_MAX_FILES", "50"))
QUICK_CLAIM_MAX_FILE_SIZE = int(os.getenv("QUICK_CLAIM_MAX_FILE_SIZE", str(10 * 1024 * 1024)))
QUICK_CLAIM_UPLOAD_RATE = os.getenv("QUICK_CLAIM_UPLOAD_RATE", "10/hour")
QUICK_CLAIM_SEND_RATE = os.getenv("QUICK_CLAIM_SEND_RATE", "20/hour")

# Allowed recipient email domains for quick claims
ALLOWED_RECIPIENT_DOMAINS = [
    d.strip() for d in os.getenv("ALLOWED_RECIPIENT_DOMAINS", "").split(",") if d.strip()
]

# Finance/CTO emails (defaults)
CTO_EMAIL = os.getenv("CTO_EMAIL", "")
FINANCE_HEAD_EMAIL = os.getenv("FINANCE_HEAD_EMAIL", "")

# REST Framework throttle rates (for reimbursement)
REST_FRAMEWORK_THROTTLE = {
    'DEFAULT_THROTTLE_RATES': {
        'quick_claim_upload': QUICK_CLAIM_UPLOAD_RATE,
        'quick_claim_send': QUICK_CLAIM_SEND_RATE,
    }
}


WHATSAPP_ENABLED = os.getenv('WHATSAPP_ENABLED', 'False').lower() == 'true'
WHATSAPP_GATEWAY_BASE_URL = os.getenv(
    'WHATSAPP_GATEWAY_BASE_URL', 'http://127.0.0.1:3005'
).rstrip('/')
WHATSAPP_DEFAULT_COUNTRY_CODE = os.getenv('WHATSAPP_DEFAULT_COUNTRY_CODE', '91')
WHATSAPP_FALLBACK_PHONE = os.getenv('WHATSAPP_FALLBACK_PHONE', '')

# If running outside Docker, replace docker service name with localhost
if not RUNNING_IN_DOCKER:
    from urllib.parse import urlparse
    parsed = urlparse(WHATSAPP_GATEWAY_BASE_URL)
    if parsed.hostname in ('whatsapp_gateway', 'whatsapp-gateway'):
        WHATSAPP_GATEWAY_BASE_URL = WHATSAPP_GATEWAY_BASE_URL.replace(
            parsed.hostname, '127.0.0.1'
        )



from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'daily-compoff-scan': {
        'task': 'leaveapp.tasks.scan_and_credit_compoff',
        'schedule': crontab(hour=23, minute=0),
    },
}