# Generated by Django 5.1 on 2026-07-24 10:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HRMSapp', '0014_alter_approvalworkflow_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text='Short code like HR, IT, SAFETY', max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Lucide icon name (e.g., shield, laptop)', max_length=50)),
                ('color_code', models.CharField(default='#3B82F6', max_length=7)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Policy Category',
                'verbose_name_plural': 'Policy Categories',
                'db_table': 'policy_categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('policy_number', models.CharField(help_text='Auto-generated: POL-HR-001', max_length=30, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True, help_text='Brief summary shown in policy library')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags for search', max_length=500)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=20)),
                ('applies_to_all', models.BooleanField(default=True, help_text='If True, all active employees receive this policy')),
                ('applicable_employee_statuses', models.CharField(default='ACTIVE,PROBATION', help_text='Comma-separated: ACTIVE,PROBATION,SUSPENDED', max_length=100)),
                ('requires_acknowledgment', models.BooleanField(default=True)),
                ('acknowledgment_deadline_days', models.IntegerField(default=14, help_text='Days after publishing to acknowledge')),
                ('is_mandatory', models.BooleanField(default=False, help_text='If True, pushed to new employees automatically (onboarding)')),
                ('acknowledgment_text', models.TextField(default='I have read and understood this policy and agree to comply with its terms.', help_text='Text shown in the acknowledgment checkbox')),
                ('review_interval_months', models.IntegerField(default=12, help_text='Review every N months (0 = no auto-review)')),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_departments', models.ManyToManyField(blank=True, limit_choices_to={'type': 'DEPARTMENT'}, related_name='applicable_policies', to='HRMSapp.companystructure')),
                ('applicable_locations', models.ManyToManyField(blank=True, limit_choices_to={'type__in': ['LOCATION', 'COMPANY']}, related_name='location_policies', to='HRMSapp.companystructure')),
                ('applicable_positions', models.ManyToManyField(blank=True, related_name='applicable_policies', to='HRMSapp.jobposition')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_policies', to='HRMSapp.employee')),
                ('policy_owner', models.ForeignKey(blank=True, help_text='Employee responsible for this policy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_policies', to='HRMSapp.employee')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='policyapp.policycategory')),
            ],
            options={
                'db_table': 'policies',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('is_visible', models.BooleanField(default=True, help_text='HR can hide inappropriate comments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_comments', to='HRMSapp.employee')),
                ('parent', models.ForeignKey(blank=True, help_text='For threaded replies', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='policyapp.policycomment')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='policyapp.policy')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_policy_comments', to='HRMSapp.employee')),
            ],
            options={
                'db_table': 'policy_comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyDistribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('distributed_at', models.DateTimeField(auto_now_add=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('first_opened_at', models.DateTimeField(blank=True, null=True)),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('total_views', models.IntegerField(default=0)),
                ('total_time_spent_seconds', models.IntegerField(default=0)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledgment_method', models.CharField(choices=[('CHECKBOX', 'Checkbox Acknowledgment'), ('SIGNATURE', 'Digital Signature')], default='CHECKBOX', max_length=20)),
                ('acknowledgment_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('deadline', models.DateField()),
                ('is_overdue', models.BooleanField(default=False)),
                ('reminders_sent', models.IntegerField(default=0)),
                ('last_reminder_at', models.DateTimeField(blank=True, null=True)),
                ('is_invalidated', models.BooleanField(default=False, help_text='Set True when policy updated — employee must re-acknowledge new version')),
                ('invalidated_at', models.DateTimeField(blank=True, null=True)),
                ('invalidation_reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_distributions', to='HRMSapp.employee')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='policyapp.policy')),
            ],
            options={
                'db_table': 'policy_distributions',
                'ordering': ['-distributed_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyReadLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('time_spent_seconds', models.IntegerField(default=0, help_text='How long the policy was open (approximate)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_logs', to='policyapp.policydistribution')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_read_logs', to='HRMSapp.employee')),
            ],
            options={
                'db_table': 'policy_read_logs',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyReminderLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reminder_type', models.CharField(choices=[('EMAIL_EMPLOYEE', 'Email to Employee'), ('NOTIFICATION_EMPLOYEE', 'In-App to Employee'), ('EMAIL_MANAGER', 'Escalation Email to Manager'), ('NOTIFICATION_MANAGER', 'Escalation Notification to Manager')], max_length=30)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('sent_to_email', models.EmailField(blank=True, max_length=254)),
                ('sent_to_name', models.CharField(blank=True, max_length=200)),
                ('days_before_deadline', models.IntegerField(default=0, help_text='Negative means days AFTER deadline (overdue)')),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='policyapp.policydistribution')),
            ],
            options={
                'db_table': 'policy_reminder_logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.CharField(help_text='Semantic version like 1.0, 1.1, 2.0', max_length=10)),
                ('content_html', models.TextField(blank=True, help_text='Rich text content')),
                ('content_file', models.FileField(blank=True, help_text='Uploaded PDF or DOCX', null=True, upload_to='policies/documents/%Y/%m/')),
                ('content_type', models.CharField(choices=[('HTML', 'Rich Text (HTML)'), ('PDF', 'PDF Upload'), ('DOCX', 'Word Document')], default='HTML', max_length=10)),
                ('change_summary', models.TextField(blank=True, help_text='What changed in this version (shown to employees)')),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('effective_from', models.DateField(help_text='This version is effective from this date')),
                ('effective_to', models.DateField(blank=True, help_text='This version is effective until this date (set when new version published)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy_versions_created', to='HRMSapp.employee')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='policyapp.policy')),
            ],
            options={
                'db_table': 'policy_versions',
                'ordering': ['policy', '-created_at'],
                'unique_together': {('policy', 'version_number')},
            },
        ),
        migrations.AddField(
            model_name='policydistribution',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='policyapp.policyversion'),
        ),
        migrations.CreateModel(
            name='PolicyApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_number', models.IntegerField()),
                ('step_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CHANGES_REQUESTED', 'Changes Requested')], default='PENDING', max_length=20)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policy_approvals', to='HRMSapp.employee')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='policyapp.policyversion')),
            ],
            options={
                'db_table': 'policy_approvals',
                'ordering': ['version', 'step_number'],
            },
        ),
        migrations.AddField(
            model_name='policy',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_policy', to='policyapp.policyversion'),
        ),
        migrations.AddIndex(
            model_name='policydistribution',
            index=models.Index(fields=['employee', 'acknowledged'], name='policy_dist_employe_82cbbc_idx'),
        ),
        migrations.AddIndex(
            model_name='policydistribution',
            index=models.Index(fields=['policy', 'acknowledged'], name='policy_dist_policy__dc3aa8_idx'),
        ),
        migrations.AddIndex(
            model_name='policydistribution',
            index=models.Index(fields=['deadline', 'is_overdue'], name='policy_dist_deadlin_6eb7df_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='policydistribution',
            unique_together={('policy', 'version', 'employee')},
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['status', 'is_active'], name='policies_status_d13d86_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['category', 'status'], name='policies_categor_3549cf_idx'),
        ),
    ]
