# Generated by Django 5.1 on 2026-07-27 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSapp', '0014_alter_approvalworkflow_module'),
        ('policyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='return_comments',
            field=models.TextField(blank=True, help_text='Comments from approver requesting changes'),
        ),
        migrations.AddField(
            model_name='policy',
            name='return_count',
            field=models.IntegerField(default=0, help_text='How many times this policy has been returned'),
        ),
        migrations.AddField(
            model_name='policy',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='returned_by',
            field=models.ForeignKey(blank=True, help_text='Approver who returned the policy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returned_policies', to='HRMSapp.employee'),
        ),
        migrations.AlterField(
            model_name='policyapproval',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned for Changes')], default='PENDING', max_length=20),
        ),
    ]
