# Generated by Django 5.1 on 2026-09-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policyapp', '0002_policy_return_comments_policy_return_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyversion',
            name='content_type',
            field=models.CharField(choices=[('HTML', 'Rich Text (HTML)'), ('PDF', 'PDF Upload'), ('DOCX', 'Word Document'), ('XLSX', 'Excel Spreadsheet')], default='HTML', max_length=10),
        ),
    ]
