# Generated by Django 5.1 on 2026-07-23 10:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HRMSapp', '0011_passwordresetotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_paid', models.BooleanField(default=True)),
                ('accrual_type', models.CharField(choices=[('YEARLY', 'Yearly (all at once)'), ('MONTHLY', 'Monthly accrual'), ('QUARTERLY', 'Quarterly accrual'), ('ON_DEMAND', 'On demand only')], default='YEARLY', max_length=20)),
                ('yearly_quota', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('accrual_per_period', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('can_carry_forward', models.BooleanField(default=False)),
                ('max_carry_forward', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('carry_forward_expiry_months', models.IntegerField(default=12)),
                ('can_encash', models.BooleanField(default=False)),
                ('max_encashment_days', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('encashment_basis', models.CharField(default='BASIC', max_length=20)),
                ('requires_document', models.BooleanField(default=False)),
                ('min_days_before_apply', models.IntegerField(default=0)),
                ('max_consecutive_days', models.IntegerField(default=0)),
                ('can_apply_half_day', models.BooleanField(default=True)),
                ('allowed_during_probation', models.BooleanField(default=False)),
                ('requires_manager_approval', models.BooleanField(default=True)),
                ('requires_hr_approval', models.BooleanField(default=False)),
                ('hr_approval_threshold_days', models.IntegerField(default=5, help_text='If leave > this many days, HR approval also required')),
                ('auto_approve', models.BooleanField(default=False)),
                ('min_service_months', models.IntegerField(default=0)),
                ('applicable_gender', models.CharField(choices=[('ALL', 'All employees'), ('MALE', 'Male only'), ('FEMALE', 'Female only')], default='ALL', max_length=10)),
                ('color_code', models.CharField(default='#3B82F6', max_length=7)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'leave_types',
                'ordering': ['display_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('date', models.DateField(db_index=True)),
                ('year', models.IntegerField(db_index=True)),
                ('holiday_type', models.CharField(choices=[('NATIONAL', 'National Holiday'), ('REGIONAL', 'Regional Holiday'), ('COMPANY', 'Company Holiday'), ('OPTIONAL', 'Optional Holiday'), ('RESTRICTED', 'Restricted Holiday')], default='NATIONAL', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('applicable_to_all_locations', models.BooleanField(default=True)),
                ('is_optional', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_locations', models.ManyToManyField(blank=True, related_name='holidays', to='HRMSapp.companystructure')),
            ],
            options={
                'db_table': 'holidays',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_number', models.CharField(max_length=30, unique=True)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('total_days', models.DecimalField(decimal_places=1, max_digits=5)),
                ('is_half_day', models.BooleanField(default=False)),
                ('half_day_period', models.CharField(blank=True, choices=[('AM', 'First Half (Morning)'), ('PM', 'Second Half (Afternoon)')], max_length=2)),
                ('reason', models.TextField()),
                ('contact_during_leave', models.CharField(blank=True, max_length=100)),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='leave_documents/%Y/%m/')),
                ('handover_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('WITHDRAWN', 'Withdrawn')], default='PENDING', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('is_lop', models.BooleanField(default=False)),
                ('lop_days', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaves_approved', to='HRMSapp.employee')),
                ('current_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaves_to_approve', to='HRMSapp.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_applications', to='HRMSapp.employee')),
                ('handover_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_handovers_received', to='HRMSapp.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leaveapp.leavetype')),
            ],
            options={
                'db_table': 'leave_applications',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveApplicationApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_number', models.IntegerField(default=1)),
                ('step_name', models.CharField(default='Manager Approval', max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='leaveapp.leaveapplication')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_approvals_pending', to='HRMSapp.employee')),
            ],
            options={
                'db_table': 'leave_application_approvals',
                'ordering': ['application', 'step_number'],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('allocated', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('accrued_till_date', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('carried_forward', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('used', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('pending', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('encashed', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('adjustment', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('last_accrual_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='HRMSapp.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leaveapp.leavetype')),
            ],
            options={
                'db_table': 'leave_balances',
                'ordering': ['-year', 'leave_type__display_order'],
                'indexes': [models.Index(fields=['employee', 'year'], name='leave_balan_employe_ee6624_idx')],
                'unique_together': {('employee', 'leave_type', 'year')},
            },
        ),
        migrations.AddIndex(
            model_name='leaveapplication',
            index=models.Index(fields=['employee', 'status'], name='leave_appli_employe_5f5e24_idx'),
        ),
        migrations.AddIndex(
            model_name='leaveapplication',
            index=models.Index(fields=['start_date', 'end_date'], name='leave_appli_start_d_424510_idx'),
        ),
        migrations.AddIndex(
            model_name='leaveapplication',
            index=models.Index(fields=['current_approver', 'status'], name='leave_appli_current_a91457_idx'),
        ),
    ]
