# Generated by Django 5.1 on 2026-07-27 13:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSapp', '0015_alter_approvalworkflow_module'),
        ('leaveapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualCalendar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField(db_index=True, unique=True)),
                ('title', models.CharField(help_text="e.g., 'Annual Calendar 2027'", max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('return_comments', models.TextField(blank=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_calendars', to='HRMSapp.employee')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_calendars', to='HRMSapp.employee')),
                ('returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returned_calendars', to='HRMSapp.employee')),
            ],
            options={
                'db_table': 'annual_calendars',
                'ordering': ['-year'],
            },
        ),
        migrations.AddField(
            model_name='holiday',
            name='calendar',
            field=models.ForeignKey(blank=True, help_text='Which annual calendar this holiday belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='leaveapp.annualcalendar'),
        ),
        migrations.CreateModel(
            name='AnnualCalendarApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_number', models.IntegerField()),
                ('step_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned for Changes')], default='PENDING', max_length=20)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calendar_approvals', to='HRMSapp.employee')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='leaveapp.annualcalendar')),
            ],
            options={
                'db_table': 'annual_calendar_approvals',
                'ordering': ['calendar', 'step_number'],
            },
        ),
    ]
