# Generated by Django 5.1 on 2026-07-28 05:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSapp', '0015_alter_approvalworkflow_module'),
        ('leaveapp', '0002_annualcalendar_holiday_calendar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarAmendment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('ADD', 'Added Holiday'), ('REMOVE', 'Removed Holiday'), ('EDIT', 'Edited Holiday')], max_length=10)),
                ('holiday_name', models.CharField(max_length=150)),
                ('holiday_date', models.DateField()),
                ('reason', models.TextField(help_text='Why this amendment was made')),
                ('made_at', models.DateTimeField(auto_now_add=True)),
                ('holiday_snapshot', models.JSONField(default=dict)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='leaveapp.annualcalendar')),
                ('made_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_amendments', to='HRMSapp.employee')),
            ],
            options={
                'db_table': 'calendar_amendments',
                'ordering': ['-made_at'],
            },
        ),
    ]
