# Generated by Django 5.1 on 2026-07-30 05:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSapp', '0015_alter_approvalworkflow_module'),
        ('leaveapp', '0003_calendaramendment'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppNotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('LEAVE_APPROVAL_REQUEST', 'Leave Approval Request'), ('LEAVE_APPROVED', 'Leave Approved'), ('LEAVE_REJECTED', 'Leave Rejected'), ('LEAVE_CANCELLED', 'Leave Cancelled')], max_length=30)),
                ('recipient_phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], max_length=20)),
                ('message_id', models.CharField(blank=True, max_length=200)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('leave_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_logs', to='leaveapp.leaveapplication')),
                ('recipient_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_notifications', to='HRMSapp.employee')),
            ],
            options={
                'db_table': 'whatsapp_notification_logs',
                'ordering': ['-sent_at'],
            },
        ),
    ]
