# Generated by Django 5.1 on 2026-07-30 11:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSapp', '0015_alter_approvalworkflow_module'),
        ('leaveapp', '0004_whatsappnotificationlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompOffCreditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credit_date', models.DateField(help_text='Date they worked (weekend/holiday)')),
                ('comp_off_days', models.DecimalField(decimal_places=1, max_digits=4)),
                ('worked_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reason', models.CharField(max_length=200)),
                ('credited_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compoff_credits', to='HRMSapp.employee')),
            ],
            options={
                'db_table': 'compoff_credit_logs',
                'ordering': ['-credit_date'],
                'unique_together': {('employee', 'credit_date')},
            },
        ),
    ]
