# Generated by Django 5.1 on 2026-07-22 11:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HRMSapp', '0011_passwordresetotp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('essl_api_url', models.URLField(blank=True)),
                ('device_serial_number', models.CharField(blank=True, max_length=120)),
                ('api_username', models.CharField(blank=True, max_length=120)),
                ('api_password_encrypted', models.TextField(blank=True)),
                ('smtp_host', models.CharField(blank=True, max_length=180)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('sender_email', models.EmailField(blank=True, max_length=254)),
                ('smtp_password_encrypted', models.TextField(blank=True)),
                ('report_receiver_email', models.EmailField(blank=True, max_length=254)),
                ('cc_emails', models.TextField(blank=True)),
                ('auto_send_time', models.TimeField(default='19:15')),
                ('enable_daily_report_email', models.BooleanField(default=False)),
                ('automation_run_mode', models.CharField(choices=[('DAILY', 'Daily'), ('MONTHLY', 'Monthly'), ('BOTH', 'Both')], default='MONTHLY', max_length=16)),
                ('shift_in_time', models.TimeField(default='09:30')),
                ('shift_out_time', models.TimeField(default='19:00')),
                ('duplicate_punch_ignore_seconds', models.PositiveIntegerField(default=60)),
                ('enable_monthly_report', models.BooleanField(default=True)),
                ('monthly_report_receiver_email', models.EmailField(blank=True, max_length=254)),
                ('monthly_cc_emails', models.TextField(blank=True)),
                ('monthly_report_start_date', models.DateField(blank=True, null=True)),
                ('monthly_report_end_date', models.DateField(blank=True, null=True)),
                ('monthly_send_day', models.CharField(default='1', max_length=2)),
                ('monthly_send_time', models.TimeField(default='09:00')),
                ('monthly_report_mode', models.CharField(choices=[('previous_month', 'Previous month'), ('current_month', 'Current month')], default='previous_month', max_length=32)),
                ('full_day_min_hours', models.DecimalField(decimal_places=2, default=8, max_digits=4)),
                ('half_day_min_hours', models.DecimalField(decimal_places=2, default=4, max_digits=4)),
                ('full_day_out_time', models.TimeField(default='18:30')),
                ('half_day_out_time', models.TimeField(default='14:00')),
                ('lunch_start_time', models.TimeField(default='13:00')),
                ('lunch_end_time', models.TimeField(default='14:00')),
                ('excluded_dates', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Automation Settings',
                'verbose_name_plural': 'Automation Settings',
                'db_table': 'attendance_automation_settings',
            },
        ),
        migrations.CreateModel(
            name='EmailReportLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_date', models.DateField(db_index=True, unique=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], max_length=16)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('report_file', models.FileField(blank=True, upload_to='attendance/reports/daily/')),
                ('error_message', models.TextField(blank=True)),
                ('total_employees_present', models.PositiveIntegerField(default=0)),
                ('late_coming', models.PositiveIntegerField(default=0)),
                ('early_exit', models.PositiveIntegerField(default=0)),
                ('missing_punch', models.PositiveIntegerField(default=0)),
                ('total_break_seconds', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'attendance_email_report_logs',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attendance_date', models.DateField(db_index=True)),
                ('employee_code', models.CharField(db_index=True, max_length=32)),
                ('employee_name', models.CharField(default='Unknown Employee', max_length=160)),
                ('punch_in', models.DateTimeField(blank=True, null=True)),
                ('punch_out', models.DateTimeField(blank=True, null=True)),
                ('total_punches', models.PositiveIntegerField(default=0)),
                ('working_hours_seconds', models.PositiveIntegerField(default=0)),
                ('break_time_seconds', models.PositiveIntegerField(default=0)),
                ('net_working_hours_seconds', models.PositiveIntegerField(default=0)),
                ('is_late', models.BooleanField(default=False)),
                ('is_early_exit', models.BooleanField(default=False)),
                ('missing_punch', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('present', 'Present'), ('missing_punch', 'Missing Punch')], default='present', max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_daily_records', to='HRMSapp.employee')),
            ],
            options={
                'db_table': 'attendance_daily',
                'ordering': ['employee_code'],
                'constraints': [models.UniqueConstraint(fields=('attendance_date', 'employee_code'), name='attendance_unique_daily_per_employee')],
            },
        ),
        migrations.CreateModel(
            name='MonthlyReportLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.PositiveSmallIntegerField(db_index=True)),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('report_file', models.FileField(blank=True, upload_to='attendance/reports/monthly/')),
                ('sent_to', models.EmailField(blank=True, max_length=254)),
                ('cc', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('success', 'Success'), ('failed', 'Failed')], default='generated', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_monthly_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attendance_monthly_report_logs',
                'ordering': ['-year', '-month', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('year', 'month'), name='attendance_unique_monthly_report')],
            },
        ),
        migrations.CreateModel(
            name='RawPunchLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_code', models.CharField(db_index=True, max_length=32)),
                ('punch_time', models.DateTimeField(db_index=True)),
                ('punch_date', models.DateField(db_index=True)),
                ('raw_line', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_raw_punches', to='HRMSapp.employee')),
            ],
            options={
                'db_table': 'attendance_raw_punch_logs',
                'ordering': ['employee_code', 'punch_time'],
                'constraints': [models.UniqueConstraint(fields=('employee_code', 'punch_time'), name='attendance_unique_raw_punch')],
            },
        ),
    ]
