# Generated by Django 5.1 on 2026-09-04 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyattendance',
            name='is_manual_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='manual_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='manual_status',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='updated_by_hr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_attendance_updates', to=settings.AUTH_USER_MODEL),
        ),
    ]
