# Generated by Django 5.1 on 2026-09-07 12:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceapp', '0002_dailyattendance_is_manual_override_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EsslDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('serial_number', models.CharField(max_length=120, unique=True)),
                ('role', models.CharField(choices=[('BOTH', 'Both (Single device - In + Out)'), ('PUNCH_IN', 'Punch In only'), ('PUNCH_OUT', 'Punch Out only')], default='BOTH', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('last_test_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_ok', models.BooleanField(default=False)),
                ('last_test_message', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'attendance_essl_devices',
                'ordering': ['role', 'name'],
            },
        ),
    ]
