# Generated by Django 5.1 on 2026-09-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceapp', '0003_essldevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationsettings',
            name='attendance_start_mode',
            field=models.CharField(choices=[('AUTO', 'Auto (from first data)'), ('MANUAL', 'Manual (fixed month)')], default='AUTO', max_length=16),
        ),
        migrations.AddField(
            model_name='automationsettings',
            name='attendance_start_month',
            field=models.CharField(blank=True, help_text='Format: YYYY-MM', max_length=7),
        ),
    ]
