# Generated by Django 5.1 on 2026-09-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceapp', '0004_automationsettings_attendance_start_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationsettings',
            name='enable_employee_self_attendance',
            field=models.BooleanField(default=False, help_text='Master switch: allow employees to self-report WFH/Site Visit attendance'),
        ),
        migrations.AddField(
            model_name='automationsettings',
            name='self_attendance_allowed_types',
            field=models.JSONField(blank=True, default=list, help_text="Statuses employees can self-report, e.g. ['WFH', 'Site Visit']"),
        ),
        migrations.AddField(
            model_name='automationsettings',
            name='self_attendance_require_approval',
            field=models.BooleanField(default=False, help_text='Phase 2 placeholder: require manager approval for self-reported entries'),
        ),
    ]
